<?php

include_once 'luz.features.inc';

/**
 * hook_menu_alter
 */
function luz_menu_alter(&$items) {
  $items['node']['page callback'] = 'luz_page_default';
}

/**
 * hook_menu
 */
function luz_menu() {
  $items['luz/copy-previous-week/%'] = array(
    'page callback' => 'luz_copy_previous_week',
    'page arguments' => array(2),
    'access arguments' => array('administer content'),
  );

  return $items;
}

function luz_page_default() {
  global $user;

  drupal_add_js(drupal_get_path('module', 'luz') . '/luz.js');
  if ($user->uid) {
    drupal_add_js(array('luz' => array('user_name' => $user->name)), 'setting');
  }

  $days = 6;
  $weeks = 4;

  $current_week = array_key_exists('week', $_GET) ? (int)$_GET['week'] : 0;
  if ($current_week < 0 || $current_week >= $weeks) {
    $current_week = 0;
  }

  // Set date to last Sunday, or next Sunday of today is Saturday.
  $start_date = new DateTime();
  $start_date->setTime(0, 0);
  $interval = $start_date->format('w') < 6 ?  '-' . $start_date->format('w') : '+1';
  $start_date->add(DateInterval::createFromDateString("$interval day"));

  $end_date = clone $start_date;
  $end_date->add(DateInterval::createFromDateString("+$weeks weeks"));

  $workshops = luz_get_workshops($start_date->getTimestamp(), $end_date->getTimestamp());

  $labels = theme('item_list', array('items' => range(8, 22), 'attributes' => array('class' => array('hour-labels'))));
  // The hour labels are added twice for when the week is shown in two rows.
  $weeks_items = array($labels . $labels);

  for ($week = 0; $week < $weeks; $week++, $start_date->add(DateInterval::createFromDateString('+1 week'))) {
    $items = array();

    $date = clone $start_date;

    for ($i = 0; $i < $days; $i++, $date->add(DateInterval::createFromDateString('+1 day'))) {

      $item = array('data' => '', 'class' => array(date('Y-m-d') == $date->format('Y-m-d') ? 'current-date' : ''));
      if ($i == 0 && user_access('administer content')) {
        $item['data'] .= l(t('Copy previous week'), 'luz/copy-previous-week/' . $date->getTimestamp(), array('attributes' => array('class' => array('copy-week'))));
      }
      $item['data'] .= '<h4>' . t($date->format('l')) . ', ' . $date->format(variable_get('date_format_shorter')) . '</h4><div class="day">';

      if (array_key_exists($date->format('Y-m-d'), $workshops)) {
        foreach ($workshops[$date->format('Y-m-d')] as $node) {
          $node_view = node_view($node);
          $node_view['field_date']['#formatter'] = 'luz_date_formatter';
          $item['data'] .= render($node_view);
        }
      }

      $item['data'] .= '</div>';

      if (user_access('create workshop content')) {
        $attributes = array(
          'attributes' => array('class' => array('add-workshop')),
          'query' => array(
            'destination' => '<front>',
            'edit[field_date][und][0][value][date]' => $date->format('m/d/Y'),
            'edit[field_date][und][0][value2][date]' => $date->format('m/d/Y'),
          ),
        );
        $item['data'] .= l(t('Add workshop'), 'node/add/workshop', $attributes);
      }

      $items[] = $item;
    }

    $weeks_items[] = theme('item_list', array('items' => $items, 'attributes' => array('id' => "week-$week", 'class' => array('luz', $week == $current_week ? 'active' : ''))));
  }
  $luz = theme('item_list', array('items' => $weeks_items, 'attributes' => array('id' => 'luz-wrapper')));

  return $luz;
}

function luz_get_workshops($start, $end) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'workshop')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldCondition('field_date', 'value', array($start, $end), 'BETWEEN')
    ->fieldOrderBy('field_date', 'value');
  $result = $query->execute();

  $by_date = array();
  $nodes = !empty($result) ? node_load_multiple(array_keys($result['node'])) : array();
  foreach ($nodes as $node) {
    $wrapper = entity_metadata_wrapper('node', $node);
    $date = date('Y-m-d', $wrapper->field_date->value->value());
    if (!array_key_exists($date, $by_date)) {
      $by_date[$date] = array();
    }
    $by_date[$date][] = $node;
  }

  return $by_date;
}

function luz_flag_flag($flag, $entity_id, $account, $flagging) {
  if ($flagging->flag_name != 'attend') {
    return;
  }

  // Only create the participant item if the flag was triggered directly by the user.
  if (isset($account->flag_from_sync)) {
    return;
  }

  $node = node_load($entity_id);
  $wrapper = entity_metadata_wrapper('node', $node);
  foreach ($wrapper->field_participants as $item) {
    if (!$item->value()) {
      continue;
    }

    if ($item->field_participant->getIdentifier() == $account->uid) {
      return;
    }
  }

  // Create a participant item and attach it to the workshop node.
  $item = entity_create('field_collection_item', array('field_name' => 'field_participants'));
  $item->setHostEntity('node', $node);
  $item->field_participant[LANGUAGE_NONE][0]['target_id'] = $account->uid;
  $wrapper->field_participants[] = $item;
  $wrapper->save();
}

function luz_flag_unflag($flag, $entity_id, $account, $flagging) {
  if ($flagging->flag_name != 'attend') {
    return;
  }

  // Only remove the participant item if the flag was triggered directly by the user.
  if (isset($account->flag_from_sync)) {
    return;
  }

  $node = node_load($entity_id);

  if ($node->field_participants) {
    foreach ($node->field_participants[LANGUAGE_NONE] as $delta => $item) {
      if (!$item = field_collection_item_load($item['value'])) {
        continue;
      }

      $wrapper = entity_metadata_wrapper('field_collection_item', $item);
      $uid = $wrapper->field_participant->getIdentifier();
      if ($uid == $account->uid) {
        unset($node->field_participants[LANGUAGE_NONE][$delta]);
        entity_delete('field_collection_item', $item->item_id);
      }
    }

    // For avoiding an endless loop when syncing after node save.
    $node->unflagged = $flagging->uid;
    node_save($node);
  }
}

function luz_count_participants($node) {
  $wrapper = entity_metadata_wrapper('node', $node);
  $count = 0;
  foreach ($wrapper->field_participants as $item) {
    if ($item->value() && $item->field_participant && $item->field_participant->value()) {
      $count++;
    }
  }

  return $count;
}

/**
 * hook_node_update
 */
function luz_node_update($node) {
  if ($node->type == 'workshop') {
    luz_sync_participants_flaggings($node);
  }
}

/**
 * hook_node_insert
 */
function luz_node_insert($node) {
  if ($node->type == 'workshop') {
    luz_sync_participants_flaggings($node);
  }
}

/**
 * hook_node_presave
 */
function luz_node_presave($node) {
  if ($node->type != 'workshop') {
    return;
  }

  $node->language = LANGUAGE_NONE;

  // Remove empty participant items.
  if (!empty($node->field_participants)) {
    foreach ($node->field_participants[LANGUAGE_NONE] as $delta => $item) {
      if (!empty($item['entity']) && $item['entity']->item_id && !$item['field_participant'][LANGUAGE_NONE][0]['target_id']) {
        unset($node->field_participants[LANGUAGE_NONE][$delta]);
        entity_delete('field_collection_item', $item['entity']->item_id);
      }
    }
  }
}

/**
 * hook_node_validate
 *
 * Make sure there are no two workshops starting at the same time.
 */
function luz_node_validate($node, $form, &$form_state) {
  if ($node->type != 'workshop') {
    return;
  }

  $wrapper = entity_metadata_wrapper('node', $node);
  $timestamp = $wrapper->field_date->value->value();

  if ($nid = luz_workshops_conflict($node)) {
    form_set_error('field_date', t("There's already another workshop (#@id) on @date starting at @time. Saving cancelled.", array('@id' => $nid, '@date' => date('j/n', $timestamp), '@time' => date('H:i', $timestamp))));
  }
}

/**
 * Check if the given workshop is conflicting with another workshop (Currently a conflict is to start at the same time).
 */
function luz_workshops_conflict($node) {
  $wrapper = entity_metadata_wrapper('node', $node);
  $timestamp = $wrapper->field_date->value->value();

  $query = new EntityFieldQuery();
  $result = $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'workshop')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldCondition('field_date', 'value', $timestamp)
    ->execute();

  if (!empty($result)) {
    $nid = key($result['node']);
    return $nid != $node->nid ? $nid : FALSE;
  }
  return FALSE;
}

function luz_sync_participants_flaggings($node) {

  // Create an array of the participants IDs and remove empty items.
  $participants = array();
  if (!empty($node->field_participants)) {
    foreach ($node->field_participants[LANGUAGE_NONE] as $item) {
      if (!$item = field_collection_item_load($item['value'])) {
        continue;
      }
      $wrapper = entity_metadata_wrapper('field_collection_item', $item);
      $uid = $wrapper->field_participant->getIdentifier();
      if ($uid) {
        $participants[$uid] = true;
      }
    }
  }

  // In case a user unflagged the node on their own, avoid calling unflag for them again.
  $flagged_by = isset($node->unflagged) ? $node->unflagged : NULL;

  $flaggings = flag_get_entity_flags('node', $node->nid, 'attend');
  $flagging_participants = array();
  foreach ($flaggings as $flagging) {
    $flagging_participants[$flagging->uid] = true;

    if ($flagged_by == $flagging->uid) {
      continue;
    }

    if (!array_key_exists($flagging->uid, $participants)) {
      $account = user_load($flagging->uid);
      $account->flag_from_sync = TRUE;
      flag('unflag', 'attend', $node->nid, $account);
    }
  }

  foreach (array_keys($participants) as $uid) {
    if (!array_key_exists($uid, $flagging_participants)) {
      $account = user_load($uid);
      $account->flag_from_sync = TRUE;
      flag('flag', 'attend', $node->nid, user_load($uid));
    }
  }
}

function luz_user_attending_workshop($workshop_node, $uid) {
  if (!$uid) {
    return FALSE;
  }

  $wrapper = entity_metadata_wrapper('node', $workshop_node);
  foreach ($wrapper->field_participants as $item) {
    if (!$item->value()) {
      continue;
    }

    if ($item->field_participant->getIdentifier() == $uid) {
      return TRUE;
    }
  }

  return FALSE;
}

function luz_flag_access($flag, $entity_id, $action, $account) {
  if ($flag->name != 'attend' || !$account->uid) {
    return;
  }

  $now = time();
  $node = node_load($entity_id);
  $node_wrapper = entity_metadata_wrapper('node', $node);

  $node_time = $node_wrapper->field_date->value->value();
  if ($node_time < $now) {
    return FALSE;
  }

  if ($action == 'flag') {
    $tid = $node_wrapper->field_type->tid->value();

    $type_access = FALSE;
    $user_wrapper = entity_metadata_wrapper('user', $account);
    foreach ($user_wrapper->field_workshop_types->value() as $term) {
      if ($term->tid == $tid) {
        $type_access = TRUE;
      }
    }

    return $type_access && luz_count_participants($node_wrapper->value()) < 5;
  }
  else {
    // No unflagging in the last 24 hours.
    if ($node_time < $now + 86400) {
      return FALSE;
    }
  }
}

function luz_copy_repeating_workshops($from_week, $to_week) {
  global $user;

  $from = new DateTime();
  $from->setTimestamp($from_week);
  $from_week_end = $from->add(DateInterval::createFromDateString('+1 week'))->getTimestamp();

  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'workshop')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldCondition('field_date', 'value', array($from_week, $from_week_end), 'BETWEEN')
    ->fieldCondition('field_repeat', 'value', TRUE)
    ->fieldOrderBy('field_date', 'value');
  $result = $query->execute();

  if (empty($result['node'])) {
    drupal_set_message(t('No repeating workshops found.'));
    return;
  }

  $weeks_delta = $to_week - $from_week;
  foreach (node_load_multiple(array_keys($result['node'])) as $original_node) {
    $values = array(
      'nid' => NULL, // auto_nodetitle is expecting an nid property.
      'type' => 'workshop',
      'uid' => $user->uid,
      'status' => NODE_PUBLISHED,
      'promote' => NODE_NOT_PROMOTED,
    );
    $new_node = entity_create('node', $values);

    $original_wrapper = entity_metadata_wrapper('node', $original_node);
    $new_wrapper = entity_metadata_wrapper('node', $new_node);

    $date = $original_wrapper->field_date->value();
    $date['value'] += $weeks_delta;
    $date['value2'] += $weeks_delta;
    $new_node->field_date[LANGUAGE_NONE][0] = $date;

    $new_wrapper->field_type->set($original_wrapper->field_type->getIdentifier());

    if (luz_workshops_conflict($new_node)) {
      continue;
    }

    foreach ($original_wrapper->field_participants as $item) {
      if (!$item->field_repeat->value()) {
        continue;
      }

      // Create an item for each participant.
      $new_item = entity_create('field_collection_item', array('field_name' => 'field_participants'));
      $new_item->setHostEntity('node', $new_node);
      $new_item->field_participant[LANGUAGE_NONE][0]['target_id'] = $item->field_participant->getIdentifier();
      $new_item->field_repeat[LANGUAGE_NONE][0]['value'] = TRUE;
      entity_save('field_collection_item', $new_item);
    }

    $new_wrapper->save();
  }
}

/**
 * hook_field_access
 *
 * Disallow normal users to access the workshop types field.
 */
function luz_field_access($op, $field, $entity_type, $entity, $account) {
  if ($field['field_name'] == 'field_workshop_types') {
    return (bool)array_intersect(array('administrator', 'content manager'), $account->roles);
  }
}

/**
 * hook_user_login
 */
function luz_user_login(&$edit, $account) {
  $edit['redirect'] = '<front>';
}

/**
 * Menu callback
 */
function luz_copy_previous_week($this_week_timestamp) {
  $previous_week = new DateTime();
  $previous_week->setTimestamp($this_week_timestamp);
  $previous_week->add(DateInterval::createFromDateString('-1 weeks'));

  luz_copy_repeating_workshops($previous_week->getTimestamp(), $this_week_timestamp);

  drupal_goto('<front>', array('query' => array('week' => 0)));
}

/**
 * hook_form_FROM_ID_alter
 */
function luz_form_workshop_node_form_alter(&$form, &$form_state) {}
